# Generated by Django 4.2.7 on 2023-11-11 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_image", models.ImageField(upload_to="images/")),
                (
                    "resized_image",
                    models.ImageField(
                        blank=True, null=True, upload_to="resized_images/"
                    ),
                ),
            ],
        ),
    ]
