# Generated by Django 4.2.7 on 2023-11-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_image_created_at_image_height_image_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="segmented_image",
            field=models.ImageField(
                blank=True, null=True, upload_to="segmented_images/"
            ),
        ),
    ]
